### ISSUE TITLE
mpq-support

### ISSUE THREAD

**Issue by ghost** [wezeku/Mpir.NET#7]
I was informed that mpq is not supported, but it seems however that there are a number of supporting functions for mpq, and the mpq_t class does exist. A few functions are missing though, e.g. mpq_numref and mpq_denref.

I tried adding them the same way as the other functions, but it didn't seem to work.

If these functions are to return mpz_t, I suspect the mpz_t needs an additional field, e.g. IsPartOfMpq, that, if true, should indicate to mpz_t.Dispose()/destructor if it should indeed dispose internally or not, or let the mpq_t.Dispose()/destructor handle it, to avoid memory corruption by the GC. mpq_t would also need hold a reference to it's mpz_t (class) numref and denref so as to return the same instance, if they were ever instantiated.

**Comment by wezeku** [comment]
Some mpq functions are carried over from X-MPIR, which Mpir.NET is based on. However, I've never tried them or written any test cases, so I'm not sure that they work. 

The reason that you weren't able to add mpq_num and mpq_den, is that they are not functions but macros. Also, as you mention, Dispose() would be a problem.

Using a field like IsPartOfMpq would be confusing, because then you would have a class that implements IDisposable (so, encourages the use of `using` in C# and `use` bindings in F#), but doesn't dispose of anything.

One possible solution might be to make the underlying value (IntPtr val) into a property defined in an interface, e.g. Impz_base, and have mpz_t implement that interface + IDisposable. Then a second class, used for mpq_num/den return values, could implement Impz_base but not IDisposable.

**Comment by emilmuller** [comment]
I can mention that I have used many of the mpq functions as well as the mpq class, and there doesn't seem to be any issues as of yet.
